/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package equationSolverUI;

import entity.History;
import entity.User;
import math.MatrixOperation;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import dbRepository.DbConnector;

/**
 *
 * @author gabri
 */
public class MathTabUI extends javax.swing.JFrame {
    User curr;
    /**
     * Creates new form MathTabUI
     * @param curr
     */
    public MathTabUI(User curr) {
        initComponents();
        this.curr = curr;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        equationText2 = new javax.swing.JTextField();
        equationText3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        equationText1 = new javax.swing.JTextField();
        equationText4 = new javax.swing.JTextField();
        equationText5 = new javax.swing.JTextField();
        cancelButton = new javax.swing.JButton();
        calculateButton = new javax.swing.JButton();
        clear2x2Button = new javax.swing.JButton();
        clear3x3Button = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Systems of Equation Calculator");

        jLabel2.setText("Equation 1:");

        jLabel3.setText("Equation 2:");
        jLabel3.setToolTipText("");

        jRadioButton1.setSelected(true);
        jRadioButton1.setText("2x2 Equations");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setText("3x3 Equations");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        equationText2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        equationText3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        equationText3.setEnabled(false);

        jLabel4.setText("Equation 1");

        jLabel5.setText("Equation 2 ");

        jLabel6.setText("Equation 3");

        equationText1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        equationText4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        equationText4.setEnabled(false);

        equationText5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        equationText5.setEnabled(false);

        cancelButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        calculateButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        calculateButton.setText("Calculate");
        calculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateButtonActionPerformed(evt);
            }
        });

        clear2x2Button.setText("Clear");
        clear2x2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear2x2ButtonActionPerformed(evt);
            }
        });

        clear3x3Button.setText("Clear");
        clear3x3Button.setEnabled(false);
        clear3x3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear3x3ButtonActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Please do not use space");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(clear3x3Button)
                .addGap(93, 93, 93))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(clear2x2Button)
                                                    .addComponent(equationText2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addGap(18, 18, 18)
                                                .addComponent(equationText1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(161, 161, 161))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(calculateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(102, 102, 102)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(jRadioButton1)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(equationText5, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(equationText4, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(equationText3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton2)
                                .addGap(35, 35, 35))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(jLabel7)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(equationText3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(34, 34, 34))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(equationText1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(equationText2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(equationText4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(equationText5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clear2x2Button))
                .addGap(18, 18, 18)
                .addComponent(clear3x3Button)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calculateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(92, 92, 92))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 * when the button 2x2 equations is selected, the text boxes of the system 2x2 are enable while 3x3 system are disabled
 */
    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        if(jRadioButton1.isSelected()){
            jRadioButton2.setSelected(false);
            
            equationText3.setEnabled(false);
            equationText4.setEnabled(false);
            equationText5.setEnabled(false);
            equationText1.setEnabled(true);
            equationText2.setEnabled(true);
            clear2x2Button.setEnabled(true);
            clear3x3Button.setEnabled(false);
        }else{
            jRadioButton2.setSelected(true);

        }
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    /**
    * when the button 3x3 equations is selected, the text boxes of the system 3x3 are enable while 2x2 system are disabled
    */
    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        if(jRadioButton2.isSelected()){
            jRadioButton1.setSelected(false);
            equationText3.setEnabled(true);
            equationText4.setEnabled(true);
            equationText5.setEnabled(true);
            equationText1.setEnabled(false);
            equationText2.setEnabled(false);
            clear2x2Button.setEnabled(false);
            clear3x3Button.setEnabled(true);
        }else{
            jRadioButton1.setSelected(true);

        }
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    /**
     * when the button "Clear" in the 2x2 equation is clicked, it erases all the filled fields so the user can start typing again.
     */
    private void clear2x2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear2x2ButtonActionPerformed
        // TODO add your handling code here:
        equationText1.setText("");
        equationText2.setText("");
        
    }//GEN-LAST:event_clear2x2ButtonActionPerformed

    /**
     * when cancel button is clicked, the program checks who the curr user is, if its admin takes it back to admin menu
     * if its user takes it back to the user menu.
     */
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        if(curr.getIsAdmin()==true){
            AdminMenuUI adminMenu = new AdminMenuUI(curr);
            adminMenu.setVisible(true);
            this.dispose();
        }else{
        UserMenuUI userMenu = new UserMenuUI(curr);
        userMenu.setVisible(true);
        this.dispose();
        }
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * when the button "Clear" in the 3x3 equation is clicked, it erases all the filled fields so the user can start typing again.
     */
    private void clear3x3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear3x3ButtonActionPerformed
        // TODO add your handling code here:
        equationText3.setText("");
        equationText4.setText("");
        equationText5.setText("");
        
    }//GEN-LAST:event_clear3x3ButtonActionPerformed

    /**
     * When the calculate button is clicked, it checks which type of system the user selected 
     * and then invokes the solving equations methods from the MatrixOperation class
     * it also saves the operation in the history table of our database, with the status 1 for completed or 2 for failed.
     * in case the input of the user is incorrect, a warning message will pop up warning the user.
     */
    private void calculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateButtonActionPerformed
        // TODO add your handling code here:
         MatrixOperation calculator = new MatrixOperation();
        DbConnector conn = new DbConnector();
        if(jRadioButton1.isSelected()){
        
            if(equationText1.getText()!= "" && equationText2.getText()!= ""){
            
                try {
                   HashMap<String,Double> resultSet =  calculator.solvingEquation2x2(equationText1.getText(), equationText2.getText());
                    JOptionPane.showMessageDialog(this, "X = " + resultSet.get("x") + "\nY = " + resultSet.get("y"));
                    conn.saveHistory2x2(new History(curr.getId(),equationText1.getText(),equationText2.getText(),1));
                    
                
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this,"Sorry, Invalid Equations");
                    conn.saveHistory2x2(new History(curr.getId(),equationText1.getText(),equationText2.getText(),2));
                    Logger.getLogger(MathTabUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        if(jRadioButton2.isSelected()){

            if(equationText3.getText()!= "" && equationText4.getText()!= "" && equationText5.getText() != ""){

                try {
                   HashMap<String,Double> resultSet =  calculator.solvingEquation3x3(equationText3.getText(), equationText4.getText(), equationText5.getText());
                    JOptionPane.showMessageDialog(this, "X = " + resultSet.get("x") + "\nY = " + resultSet.get("y") + "\nZ = " + resultSet.get("z"));
                    conn.saveHistory3x3(new History(curr.getId(),equationText3.getText(),equationText4.getText(),equationText5.getText(),1));
                    
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this,"Sorry, Invalid Equations");
                    conn.saveHistory3x3(new History(curr.getId(),equationText3.getText(),equationText4.getText(),equationText5.getText(),2));
                    Logger.getLogger(MathTabUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }


        }
    }//GEN-LAST:event_calculateButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MathTabUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MathTabUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MathTabUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MathTabUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new MathTabUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calculateButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton clear2x2Button;
    private javax.swing.JButton clear3x3Button;
    private javax.swing.JTextField equationText1;
    private javax.swing.JTextField equationText2;
    private javax.swing.JTextField equationText3;
    private javax.swing.JTextField equationText4;
    private javax.swing.JTextField equationText5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    // End of variables declaration//GEN-END:variables
}
